version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d  # Mount the SQL scripts directory

  moe: 
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db:5432/moe?sslmode=disable"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom Nginx configuration file
    ports:
      - "80:80"
    depends_on:
      - moe  
volumes:
  postgres-data: